// app/src/auth/Login.tsx
// Login screen — email + password, sign-in / sign-up toggle. Uses Firebase Auth
// when configured; otherwise any credentials sign in (demo mode).
import { useState, type FormEvent } from 'react';
import { Button, Input } from '../ds-vendor/components';
import { di } from '../lib/icon';
import { useAuth } from '../lib/auth';
import { firebaseConfigured } from '../lib/firebase';

export function Login() {
  const { signIn, signUp } = useAuth();
  const [email, setEmail] = useState('dana.reyes@example.com');
  const [pw, setPw] = useState('demo1234');
  const [mode, setMode] = useState<'in' | 'up'>('in');
  const [err, setErr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    if (!email.trim() || busy) return;
    setBusy(true);
    setErr(null);
    try {
      if (mode === 'in') await signIn(email.trim(), pw);
      else await signUp(email.trim(), pw);
    } catch (ex) {
      const msg = ex instanceof Error ? ex.message : 'Could not sign in.';
      setErr(msg.replace('Firebase: ', ''));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div
      style={{
        minHeight: '100dvh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        background: 'var(--surface-page)',
      }}
    >
      <div className="ps-fade" style={{ width: '100%', maxWidth: 384 }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 11,
            justifyContent: 'center',
            marginBottom: 8,
          }}
        >
          <img src="/assets/logo-mark.svg" width={38} height={38} alt="" />
          <span
            style={{
              fontSize: 'var(--text-xl)',
              fontWeight: 700,
              letterSpacing: '-0.02em',
              color: 'var(--text-heading)',
            }}
          >
            Property Suite
          </span>
        </div>
        <p
          style={{
            textAlign: 'center',
            color: 'var(--text-muted)',
            fontSize: 'var(--text-sm)',
            margin: '0 0 24px',
          }}
        >
          {mode === 'in'
            ? 'Sign in to manage your portfolio'
            : 'Create your landlord account'}
        </p>
        <div
          style={{
            background: 'var(--surface-card)',
            border: '1px solid var(--border-default)',
            borderRadius: 'var(--radius-lg)',
            boxShadow: 'var(--shadow-sm)',
            padding: 24,
          }}
        >
          <form
            onSubmit={submit}
            style={{ display: 'flex', flexDirection: 'column', gap: 14 }}
          >
            <Input
              label="Email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
              leadingIcon={di('mail')}
              autoComplete="email"
            />
            <Input
              label="Password"
              type="password"
              value={pw}
              onChange={(e) => setPw(e.target.value)}
              placeholder="••••••••"
              leadingIcon={di('lock')}
              autoComplete={mode === 'in' ? 'current-password' : 'new-password'}
            />
            {err ? (
              <div
                style={{
                  fontSize: 'var(--text-sm)',
                  color: 'var(--danger-fg)',
                  background: 'var(--danger-bg)',
                  border: '1px solid color-mix(in srgb, var(--danger-solid) 30%, transparent)',
                  borderRadius: 'var(--radius-md)',
                  padding: '9px 12px',
                }}
              >
                {err}
              </div>
            ) : null}
            <Button
              type="submit"
              variant="primary"
              fullWidth
              size="lg"
              disabled={busy}
              style={{ marginTop: 4 }}
            >
              {busy
                ? 'Please wait…'
                : mode === 'in'
                  ? 'Sign in'
                  : 'Create account'}
            </Button>
          </form>
          <div
            style={{
              marginTop: 16,
              textAlign: 'center',
              fontSize: 'var(--text-sm)',
              color: 'var(--text-muted)',
            }}
          >
            {mode === 'in' ? 'New here? ' : 'Already have an account? '}
            <button
              type="button"
              onClick={() => {
                setErr(null);
                setMode((m) => (m === 'in' ? 'up' : 'in'));
              }}
              style={{
                background: 'none',
                border: 'none',
                padding: 0,
                cursor: 'pointer',
                color: 'var(--text-link)',
                fontWeight: 600,
                fontSize: 'inherit',
              }}
            >
              {mode === 'in' ? 'Create an account' : 'Sign in'}
            </button>
          </div>
        </div>
        <p
          style={{
            textAlign: 'center',
            color: 'var(--text-faint)',
            fontSize: 'var(--text-xs)',
            marginTop: 18,
          }}
        >
          {firebaseConfigured
            ? 'Secured by Firebase Authentication'
            : 'Demo · any email and password will sign you in'}
        </p>
      </div>
    </div>
  );
}

// project/angular-property-suite/src/app/components/login/login.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Output,
} from '@angular/core';
import { User } from '../../models/user.model';
import { AuthService } from '../../services/auth.service';
import { FormFieldComponent } from '../form-field/form-field.component';
import { UiButtonComponent } from '../ui-button/ui-button.component';

type AuthMode = 'in' | 'up';

/**
 * Sign-in / sign-up card. Demo only — any email + password authenticates.
 * Emits the resulting `User` so the root can flip to the launcher.
 */
@Component({
  selector: 'ps-login',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormFieldComponent, UiButtonComponent],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  /** Fires with the authenticated user on successful submit. */
  @Output() authed = new EventEmitter<User>();

  email = 'dana.reyes@example.com';
  password = 'demo1234';
  mode: AuthMode = 'in';

  constructor(private readonly auth: AuthService) {}

  get heading(): string {
    return this.mode === 'in'
      ? 'Sign in to manage your portfolio'
      : 'Create your landlord account';
  }

  get submitLabel(): string {
    return this.mode === 'in' ? 'Sign in' : 'Create account';
  }

  toggleMode(): void {
    this.mode = this.mode === 'in' ? 'up' : 'in';
  }

  submit(event: Event): void {
    event.preventDefault();
    const email = this.email.trim();
    if (!email) return;
    this.authed.emit(this.auth.signIn(email));
  }
}

<div class="login">
  <div class="login__inner ps-fade">
    <div class="login__brand">
      <img src="assets/logo-mark.svg" width="38" height="38" alt="" />
      <span class="login__wordmark">Property Suite</span>
    </div>
    <p class="login__subtitle">{{ heading }}</p>

    <div class="login__card">
      <form class="login__form" (submit)="submit($event)">
        <ps-form-field
          label="Email"
          type="email"
          leadingIcon="mail"
          autocomplete="email"
          placeholder="you@example.com"
          [(value)]="email"
        ></ps-form-field>

        <ps-form-field
          label="Password"
          type="password"
          leadingIcon="lock"
          autocomplete="current-password"
          placeholder="••••••••"
          [(value)]="password"
        ></ps-form-field>

        <ps-button class="login__submit" type="submit" variant="primary" size="lg" [fullWidth]="true">
          {{ submitLabel }}
        </ps-button>
      </form>

      <div class="login__switch">
        {{ mode === 'in' ? 'New here? ' : 'Already have an account? ' }}
        <button type="button" class="login__switch-btn" (click)="toggleMode()">
          {{ mode === 'in' ? 'Create an account' : 'Sign in' }}
        </button>
      </div>
    </div>

    <p class="login__demo">Demo · any email and password will sign you in</p>
  </div>
</div>
