// project/angular-property-suite/src/app/features/rent/charts.component.ts
import { ChangeDetectionStrategy, Component, Input, inject } from '@angular/core';
import { CurrencyService } from '../../../services/currency.service';
import { DonutDatum, SeriesPoint } from '../../../models/rent.vm';

/**
 * Grouped income/expense bars, ported from `GroupedBars`. Brand-green income
 * bars and amber expense bars, 6 months, month labels on the x-axis.
 *
 * @example <app-grouped-bars [series]="rent.series" />
 */
@Component({
  selector: 'app-grouped-bars',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="bars">
      @for (s of series; track s.m) {
        <div class="bars__group">
          <div class="bars__stack">
            <div
              class="bars__bar bars__bar--income"
              [style.height.%]="(s.income / max) * 100"
              [title]="'Income ' + currency.format(s.income)"
            ></div>
            <div
              class="bars__bar bars__bar--expense"
              [style.height.%]="(s.expense / max) * 100"
              [title]="'Expenses ' + currency.format(s.expense)"
            ></div>
          </div>
          <span class="bars__label">{{ s.m }}</span>
        </div>
      }
    </div>
  `,
  styles: [
    `
      .bars {
        display: flex;
        align-items: flex-end;
        gap: 18px;
        height: 200px;
        padding: 8px 0;
      }
      .bars__group {
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 8px;
      }
      .bars__stack {
        display: flex;
        align-items: flex-end;
        justify-content: center;
        gap: 5px;
        height: 170px;
        width: 100%;
      }
      .bars__bar {
        width: 38%;
        max-width: 22px;
        border-radius: 4px 4px 0 0;
      }
      .bars__bar--income {
        background: var(--brand);
      }
      .bars__bar--expense {
        background: var(--amber-400);
      }
      .bars__label {
        font-size: var(--text-xs);
        font-weight: var(--weight-semibold);
        color: var(--text-muted);
      }
    `,
  ],
})
export class GroupedBarsComponent {
  @Input({ required: true }) series: SeriesPoint[] = [];
  readonly currency = inject(CurrencyService);

  get max(): number {
    return Math.max(...this.series.flatMap((s) => [s.income, s.expense]));
  }
}

interface DonutSeg {
  color: string;
  dash: string;
  offset: number;
}

/**
 * Proportional donut ring with a center total, ported from `Donut`.
 *
 * @example <app-donut [data]="rent.donutData()" [total]="total" caption="June total" />
 */
@Component({
  selector: 'app-donut',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="donut">
      <svg width="168" height="168" viewBox="0 0 140 140" class="donut__svg">
        @for (seg of segments; track $index) {
          <circle
            cx="70"
            cy="70"
            r="52"
            fill="none"
            [attr.stroke]="seg.color"
            stroke-width="18"
            [attr.stroke-dasharray]="seg.dash"
            [attr.stroke-dashoffset]="seg.offset"
          ></circle>
        }
      </svg>
      <div class="donut__center">
        <span class="donut__caption">{{ caption }}</span>
        <span class="ps-mono donut__total">{{ currency.format(total) }}</span>
      </div>
    </div>
  `,
  styles: [
    `
      .donut {
        position: relative;
        width: 168px;
        height: 168px;
        flex: none;
      }
      .donut__svg {
        transform: rotate(-90deg);
      }
      .donut__center {
        position: absolute;
        inset: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
      .donut__caption {
        font-size: var(--text-xs);
        font-weight: var(--weight-semibold);
        color: var(--text-muted);
      }
      .donut__total {
        font-size: 16px;
        font-weight: var(--weight-bold);
        color: var(--text-heading);
      }
    `,
  ],
})
export class DonutComponent {
  @Input({ required: true }) data: DonutDatum[] = [];
  @Input({ required: true }) total = 0;
  @Input() caption = 'Total';
  readonly currency = inject(CurrencyService);

  private readonly C = 2 * Math.PI * 52;

  get segments(): DonutSeg[] {
    let off = 0;
    return this.data.map((d) => {
      const frac = this.total ? d.value / this.total : 0;
      const seg: DonutSeg = {
        color: d.color,
        dash: `${frac * this.C} ${this.C}`,
        offset: -off,
      };
      off += frac * this.C;
      return seg;
    });
  }
}

// app/src/apps/rent/charts.tsx
// Rent Tracker — popover, period drum picker, and charts (port of rent-charts.jsx).
import { useEffect, useRef, type CSSProperties, type ReactNode } from 'react';
import { Button } from '../../ds-vendor/components';
import { MONTH_NAMES, gbp, type SeriesPoint } from './data';

/* ---------- popover ---------- */
export function Popover({
  open,
  onClose,
  children,
  align = 'left',
  style,
}: {
  open: boolean;
  onClose: () => void;
  children: ReactNode;
  align?: 'left' | 'right';
  style?: CSSProperties;
}) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const h = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) onClose();
    };
    const id = setTimeout(() => document.addEventListener('mousedown', h));
    return () => {
      clearTimeout(id);
      document.removeEventListener('mousedown', h);
    };
  }, [open, onClose]);
  if (!open) return null;

  // Centered mode: when the caller passes a translateX(-50%) transform we lift the
  // popover to a screen-centered fixed overlay (per the period-picker tweak).
  const centered =
    typeof style?.transform === 'string' && style.transform.includes('translateX(-50%)');

  const base: CSSProperties = centered
    ? {
        position: 'fixed',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: 200,
      }
    : {
        position: 'absolute',
        top: 'calc(100% + 8px)',
        [align]: 0,
        zIndex: 100,
      };

  const { transform: _t, left: _l, ...rest } = style ?? {};

  return (
    <div
      ref={ref}
      className="ps-fade"
      style={{
        ...base,
        background: 'var(--surface-card)',
        border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-md)',
        boxShadow: 'var(--shadow-md)',
        minWidth: 200,
        overflow: 'hidden',
        ...rest,
      }}
    >
      {children}
    </div>
  );
}

/* ---------- period drum picker ---------- */
export function PeriodPicker({
  month,
  year,
  onPick,
  onClose,
}: {
  month: number;
  year: number;
  onPick: (m: number, y: number) => void;
  onClose: () => void;
}) {
  const years = [2024, 2025, 2026, 2027];
  const Col = ({
    items,
    val,
    fmt,
    set,
  }: {
    items: number[];
    val: number;
    fmt?: (i: number) => ReactNode;
    set: (i: number) => void;
  }) => (
    <div
      className="ps-scroll-x"
      style={{ maxHeight: 220, overflowY: 'auto', flex: 1, padding: 4 }}
    >
      {items.map((it) => {
        const on = it === val;
        return (
          <button
            key={it}
            onClick={() => set(it)}
            style={{
              display: 'block',
              width: '100%',
              padding: '9px 12px',
              border: 'none',
              cursor: 'pointer',
              textAlign: 'center',
              borderRadius: 'var(--radius-sm)',
              background: on ? 'var(--brand-tint)' : 'transparent',
              color: on ? 'var(--brand-on-tint)' : 'var(--text-body)',
              fontSize: 'var(--text-sm)',
              fontWeight: on ? 700 : 500,
            }}
          >
            {fmt ? fmt(it) : it}
          </button>
        );
      })}
    </div>
  );
  return (
    <div style={{ width: 280 }}>
      <div style={{ display: 'flex', gap: 4, padding: 6 }}>
        <Col
          items={MONTH_NAMES.map((_, i) => i)}
          val={month}
          fmt={(i) => MONTH_NAMES[i]}
          set={(m) => onPick(m, year)}
        />
        <div style={{ width: 1, background: 'var(--border-subtle)' }} />
        <Col items={years} val={year} set={(y) => onPick(month, y)} />
      </div>
      <div
        style={{
          padding: 10,
          borderTop: '1px solid var(--border-subtle)',
          display: 'flex',
          justifyContent: 'flex-end',
        }}
      >
        <Button size="sm" variant="primary" onClick={onClose}>
          Done
        </Button>
      </div>
    </div>
  );
}

/* ---------- charts ---------- */
export function GroupedBars({ series }: { series: SeriesPoint[] }) {
  const max = Math.max(...series.flatMap((s) => [s.income, s.expense]));
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'flex-end',
        gap: 18,
        height: 200,
        padding: '8px 0',
      }}
    >
      {series.map((s) => (
        <div
          key={s.m}
          style={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 8,
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'flex-end',
              gap: 5,
              height: 170,
              width: '100%',
              justifyContent: 'center',
            }}
          >
            <div
              title={'Income ' + gbp(s.income)}
              style={{
                width: '38%',
                maxWidth: 22,
                height: (s.income / max) * 100 + '%',
                background: 'var(--brand)',
                borderRadius: '4px 4px 0 0',
              }}
            />
            <div
              title={'Expenses ' + gbp(s.expense)}
              style={{
                width: '38%',
                maxWidth: 22,
                height: (s.expense / max) * 100 + '%',
                background: 'var(--amber-400)',
                borderRadius: '4px 4px 0 0',
              }}
            />
          </div>
          <span
            style={{
              fontSize: 'var(--text-xs)',
              color: 'var(--text-muted)',
              fontWeight: 600,
            }}
          >
            {s.m}
          </span>
        </div>
      ))}
    </div>
  );
}

export function Donut({
  data,
  total,
}: {
  data: Array<{ id: string; color: string; value: number }>;
  total: number;
}) {
  const C = 2 * Math.PI * 52;
  let off = 0;
  return (
    <div style={{ position: 'relative', width: 168, height: 168, flex: 'none' }}>
      <svg width="168" height="168" viewBox="0 0 140 140" style={{ transform: 'rotate(-90deg)' }}>
        {data.map((d) => {
          const frac = d.value / total;
          const seg = (
            <circle
              key={d.id}
              cx="70"
              cy="70"
              r="52"
              fill="none"
              stroke={d.color}
              strokeWidth="18"
              strokeDasharray={`${frac * C} ${C}`}
              strokeDashoffset={-off}
            />
          );
          off += frac * C;
          return seg;
        })}
      </svg>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <span
          style={{
            fontSize: 'var(--text-xs)',
            color: 'var(--text-muted)',
            fontWeight: 600,
          }}
        >
          June total
        </span>
        <span
          className="ps-mono"
          style={{
            fontSize: 'var(--text-2xl)',
            fontWeight: 700,
            color: 'var(--text-heading)',
          }}
        >
          {gbp(total)}
        </span>
      </div>
    </div>
  );
}
