// angular/src/app/features/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { environment } from '../../../environments/environment';

const isConfigured = environment.firebaseConfig.apiKey !== 'YOUR_API_KEY';

@Component({
  selector: 'ps-login',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="ps-fade" style="min-height:100dvh;display:flex;align-items:center;justify-content:center;background:var(--surface-page);padding:24px;">
      <div style="width:100%;max-width:400px;display:flex;flex-direction:column;gap:24px;">
        <!-- Logo -->
        <div style="text-align:center;">
          <div style="display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;background:var(--brand);border-radius:var(--radius-md);margin-bottom:12px;">
            <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>
              <polyline points="9 22 9 12 15 12 15 22"/>
            </svg>
          </div>
          <h1 style="margin:0;font-size:var(--text-xl);font-weight:700;color:var(--text-heading);">PropertySuite</h1>
          <p style="margin:6px 0 0;color:var(--text-muted);font-size:var(--text-sm);">
            {{ mode() === 'in' ? 'Sign in to your account' : 'Create an account' }}
          </p>
        </div>

        <!-- Card -->
        <div style="background:var(--surface-card);border:1px solid var(--border-default);border-radius:var(--radius-lg);padding:28px;box-shadow:var(--shadow-sm);">
          <form (ngSubmit)="submit()" style="display:flex;flex-direction:column;gap:14px;">
            <!-- Email -->
            <div style="display:flex;flex-direction:column;gap:6px;">
              <label style="font-size:var(--text-sm);font-weight:600;color:var(--text-heading);">Email</label>
              <input
                type="email"
                class="ps-input"
                [(ngModel)]="email"
                name="email"
                placeholder="you@example.com"
                autocomplete="email"
                required
                data-testid="input-email"
              />
            </div>

            <!-- Password -->
            <div style="display:flex;flex-direction:column;gap:6px;">
              <label style="font-size:var(--text-sm);font-weight:600;color:var(--text-heading);">Password</label>
              <input
                type="password"
                class="ps-input"
                [(ngModel)]="password"
                name="password"
                placeholder="••••••••"
                autocomplete="current-password"
                required
                data-testid="input-password"
              />
            </div>

            <!-- Error -->
            @if (err()) {
              <div style="background:var(--danger-bg);color:var(--danger-fg);border-radius:var(--radius-md);padding:10px 14px;font-size:var(--text-sm);" data-testid="login-error">
                {{ err() }}
              </div>
            }

            <!-- Submit -->
            <button
              type="submit"
              class="ps-btn ps-btn-primary"
              style="width:100%;margin-top:4px;"
              [disabled]="busy()"
              data-testid="btn-submit"
            >
              @if (busy()) {
                <span class="ps-spin" style="width:18px;height:18px;border-width:2px;"></span>
              } @else {
                {{ mode() === 'in' ? 'Sign in' : 'Create account' }}
              }
            </button>
          </form>
        </div>

        <!-- Toggle -->
        <p style="text-align:center;font-size:var(--text-sm);color:var(--text-muted);margin:0;">
          @if (mode() === 'in') {
            Don't have an account?
            <button (click)="toggleMode()" style="background:none;border:none;color:var(--brand);font-weight:600;cursor:pointer;padding:0;" data-testid="btn-toggle-mode">Sign up</button>
          } @else {
            Already have an account?
            <button (click)="toggleMode()" style="background:none;border:none;color:var(--brand);font-weight:600;cursor:pointer;padding:0;" data-testid="btn-toggle-mode">Sign in</button>
          }
        </p>

        <!-- Footer note -->
        <p style="text-align:center;font-size:var(--text-xs);color:var(--text-faint);margin:0;">
          @if (isConfigured) {
            Secured by Firebase Authentication
          } @else {
            Demo mode — any email &amp; password will work
          }
        </p>
      </div>
    </div>
  `,
})
export class LoginComponent {
  private auth = inject(AuthService);
  private router = inject(Router);

  readonly isConfigured = isConfigured;
  readonly mode = signal<'in' | 'up'>('in');
  readonly err = signal<string | null>(null);
  readonly busy = signal(false);

  email = '';
  password = '';

  toggleMode(): void {
    this.mode.update((m) => (m === 'in' ? 'up' : 'in'));
    this.err.set(null);
  }

  async submit(): Promise<void> {
    this.err.set(null);
    this.busy.set(true);
    try {
      if (this.mode() === 'in') {
        await this.auth.signIn(this.email, this.password);
      } else {
        await this.auth.signUp(this.email, this.password);
      }
      this.router.navigate(['/']);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      this.err.set(msg.replace('Firebase: ', '').replace(/\s*\(.*\)/, ''));
    } finally {
      this.busy.set(false);
    }
  }
}

// app/src/auth/Login.tsx
// Login screen — email + password, sign-in / sign-up toggle. Uses Firebase Auth
// when configured; otherwise any credentials sign in (demo mode).
import { useState, type FormEvent } from 'react';
import { Button, Input } from '../ds-vendor/components';
import { di } from '../lib/icon';
import { useAuth } from '../lib/auth';
import { firebaseConfigured } from '../lib/firebase';

export function Login() {
  const { signIn, signUp } = useAuth();
  const [email, setEmail] = useState('dana.reyes@example.com');
  const [pw, setPw] = useState('demo1234');
  const [mode, setMode] = useState<'in' | 'up'>('in');
  const [err, setErr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    if (!email.trim() || busy) return;
    setBusy(true);
    setErr(null);
    try {
      if (mode === 'in') await signIn(email.trim(), pw);
      else await signUp(email.trim(), pw);
    } catch (ex) {
      const msg = ex instanceof Error ? ex.message : 'Could not sign in.';
      setErr(msg.replace('Firebase: ', ''));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div
      style={{
        minHeight: '100dvh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        background: 'var(--surface-page)',
      }}
    >
      <div className="ps-fade" style={{ width: '100%', maxWidth: 384 }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 11,
            justifyContent: 'center',
            marginBottom: 8,
          }}
        >
          <img src="/assets/logo-mark.svg" width={38} height={38} alt="" />
          <span
            style={{
              fontSize: 'var(--text-xl)',
              fontWeight: 700,
              letterSpacing: '-0.02em',
              color: 'var(--text-heading)',
            }}
          >
            Property Suite
          </span>
        </div>
        <p
          style={{
            textAlign: 'center',
            color: 'var(--text-muted)',
            fontSize: 'var(--text-sm)',
            margin: '0 0 24px',
          }}
        >
          {mode === 'in'
            ? 'Sign in to manage your portfolio'
            : 'Create your landlord account'}
        </p>
        <div
          style={{
            background: 'var(--surface-card)',
            border: '1px solid var(--border-default)',
            borderRadius: 'var(--radius-lg)',
            boxShadow: 'var(--shadow-sm)',
            padding: 24,
          }}
        >
          <form
            onSubmit={submit}
            style={{ display: 'flex', flexDirection: 'column', gap: 14 }}
          >
            <Input
              label="Email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
              leadingIcon={di('mail')}
              autoComplete="email"
            />
            <Input
              label="Password"
              type="password"
              value={pw}
              onChange={(e) => setPw(e.target.value)}
              placeholder="••••••••"
              leadingIcon={di('lock')}
              autoComplete={mode === 'in' ? 'current-password' : 'new-password'}
            />
            {err ? (
              <div
                style={{
                  fontSize: 'var(--text-sm)',
                  color: 'var(--danger-fg)',
                  background: 'var(--danger-bg)',
                  border: '1px solid color-mix(in srgb, var(--danger-solid) 30%, transparent)',
                  borderRadius: 'var(--radius-md)',
                  padding: '9px 12px',
                }}
              >
                {err}
              </div>
            ) : null}
            <Button
              type="submit"
              variant="primary"
              fullWidth
              size="lg"
              disabled={busy}
              style={{ marginTop: 4 }}
            >
              {busy
                ? 'Please wait…'
                : mode === 'in'
                  ? 'Sign in'
                  : 'Create account'}
            </Button>
          </form>
          <div
            style={{
              marginTop: 16,
              textAlign: 'center',
              fontSize: 'var(--text-sm)',
              color: 'var(--text-muted)',
            }}
          >
            {mode === 'in' ? 'New here? ' : 'Already have an account? '}
            <button
              type="button"
              onClick={() => {
                setErr(null);
                setMode((m) => (m === 'in' ? 'up' : 'in'));
              }}
              style={{
                background: 'none',
                border: 'none',
                padding: 0,
                cursor: 'pointer',
                color: 'var(--text-link)',
                fontWeight: 600,
                fontSize: 'inherit',
              }}
            >
              {mode === 'in' ? 'Create an account' : 'Sign in'}
            </button>
          </div>
        </div>
        <p
          style={{
            textAlign: 'center',
            color: 'var(--text-faint)',
            fontSize: 'var(--text-xs)',
            marginTop: 18,
          }}
        >
          {firebaseConfigured
            ? 'Secured by Firebase Authentication'
            : 'Demo · any email and password will sign you in'}
        </p>
      </div>
    </div>
  );
}
